version: '3.8'
services:
  node:
    build: .
    image: shoese-commerce
    environment:
       NODE_ENV: development
       PORT: 5000
       MONGO_URL: mongodb://mongodb:27017/khutta-ma-jutta
       JWT_SECRET: asdfghjkl123
       JWT_EXPIRE: 1d
       JWT_COOKIE_EXPIRE: 2
       COMPANY: bregmi06@gmail.com
    ports:
      - '5000:5000'
    depends_on:
      - mongodb

    networks:
      - shoes-network

  mongodb:
    image: mongo:6-jammy
    ports:
      - '27017:27017'
    volumes:
      - dbdata6:/data/db
    networks:
      - shoes-network

volumes:
  dbdata6:

networks:
  shoes-network:
    driver: bridge